---
# file: roles/common/tasks/main.yml

- name: ensure common packages are present
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - iftop
    - htop
    - vim

- name: ensure the bashrc file is present
  copy: src=home/bashrc dest=/home/vagrant/.bashrc mode=0700 owner=vagrant group=vagrant

- name: Dump all variables
  connection: local
  local_action: template src=environment.j2 dest={{ inventory_dir }}/environment.log
  sudo: no
